folder_in: /home/user/tst/file
folder_out: /home/user/tst/out
folder_ext: /home/user/tst/ext
folder_badarx: /home/user/tst/badarx
size_file: 1M
count_files: 3
config_file: config.yaml
stat_file: /proc/loadavg
output_file: stat.txt
